### ISSUE TITLE
CAR pixelization notebooks

### ISSUE THREAD

**Issue by zonca** [simonsobs/mapsims_tutorials#1]
@msyriac you can use this repository

**Comment by msyriac** [comment]
Ok, thanks will push here for now. @mhasself started https://github.com/simonsobs/pwg-tutorials .  You guys can iterate on where things should end up eventually.

**Comment by zonca** [comment]
Start numbering notebooks at 6

**Comment by zonca** [comment]
@msyriac please post empty notebooks

**Comment by zonca** [comment]
i.e. with no output cells

**Comment by msyriac** [comment]
My bad, will do in the future.
