### ISSUE TITLE
Created MBS kernel

### ISSUE THREAD

**Issue by zonca** [simonsobs/mapsims_tutorials#2]
@msyriac I prefer to use my own kernel only for MBS, it is easier and has only the basic packages.
I ran your notebook and it worked fine.

see instruction in the README on how to install it.

Please let me know if anything is not working or you need any other package.

**Comment by zonca** [comment]
@tskisner @keskitalo @mhasself @aiolasimone I got too anxious...I created my own kernel. I am going to use this for the MBS tutorial on Wednesday. See README of this repo for more details.

**Comment by tskisner** [comment]
Do what you want.  I still need to set up the installation for the rest of the tutorials.  Also note that I'm not doing a one-off installation of things- I'm writing scripts to easily install everything over and over.  Because we will need to do that, perhaps several times over the next week or so.

**Comment by msyriac** [comment]
@zonca I get No module named 'mapsims' when using the MBS kernel.

**Comment by zonca** [comment]
@msyriac are you sure you are using the right kernel? "Simons Obs MBS"

**Comment by msyriac** [comment]
Yep, I am. And now it doesn't load pixell either.

**Comment by zonca** [comment]
can you do:

```
import sys
print(sys.path)
```

```
cori[cori12] /global/common/software/sobs/mbs/lib/python3.7/site-packages$ pwd
/global/common/software/sobs/mbs/lib/python3.7/site-packages
cori[cori12] /global/common/software/sobs/mbs/lib/python3.7/site-packages$ ls -ld mapsims pixell
drwxrws--- 6 sobs sobs 2048 Jun 22 21:00 mapsims
drwxrws--- 3 sobs sobs 2048 Jun 22 21:00 pixell
```

**Comment by msyriac** [comment]
In the JyupyterHub notebook with the Simons Obs MBS kernel:
```
import sys
print(sys.path)

['/global/u2/m/msyriac/repos/mapsims_tutorials', '', '/opt/ovis/lib/python2.7/site-packages', '/usr/common/software/python/3.7-anaconda-2019.10/lib/python37.zip', '/usr/common/software/python/3.7-anaconda-2019.10/lib/python3.7', '/usr/common/software/python/3.7-anaconda-2019.10/lib/python3.7/lib-dynload', '/usr/common/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages', '/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages', '/usr/common/software/python/3.7-anaconda-2019.10/lib/python3.7/site-packages/IPython/extensions', '/global/u2/m/msyriac/.ipython']
```

**Comment by zonca** [comment]
I added a check for the `mbs` kernel in notebook 0 of the tutorial, this is not the MBS kernel.
did you run my script to install it?

**Comment by zonca** [comment]
do `cat ~/.local/share/jupyter/kernels/sobs-mbs/kernel.json`

**Comment by zonca** [comment]
it should be:

```
cat ~/.local/share/jupyter/kernels/sobs-mbs/ke
rnel.json
{
 "argv": [
  "/global/common/software/sobs/mbs/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Simons Obs MBS",
 "language": "python"
```

**Comment by msyriac** [comment]
![2020-06-23_14:10:07](https://user-images.githubusercontent.com/3674397/85439757-528f5d00-b55b-11ea-8a50-6ec28cf99e0a.png)

```
$ cat ~/.local/share/jupyter/kernels/sobs-mbs/kernel.json
{
 "argv": [
  "/usr/common/software/python/3.7-anaconda-2019.10/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Simons Obs MBS",
 "language": "python"
}

```

**Comment by zonca** [comment]
ok for now modify kernel.json

setting `/global/common/software/sobs/mbs/bin/python`
then I'll figure out what is wrong in the installation script

**Comment by msyriac** [comment]
It works after git pulling and reinstalling, thanks!
