### ISSUE TITLE
Review my notebooks, update kernel

### ISSUE THREAD

**Issue by zonca** [simonsobs/mapsims_tutorials#3]
@msyriac I have completed my notebooks, would you like to check them out and provide feedback?

consider that they need `mapsims` master which is not yet on the MBS kernel.

Later tonight, around 8pm PT (or earlier if you think you don't need any other changes), I'll package so_pysm_models and mapsims and install them in the MBS kernel and test all notebooks (mine and yours)

**Comment by msyriac** [comment]
Maybe set iter=0 in anafast, since we're not interested in precision, just a quick power spectrum.

**Comment by msyriac** [comment]
Could add a title to every notebook, since the full filename is not easily visible.

**Comment by msyriac** [comment]
I get errors in Notebook 5 because the kernel has out-of-date mapsims.  Please feel free to update the kernel; I don't think I'll need more changes. Also, in case it looks like Notebook 6+7 won't get 25-30 minutes, I would say Notebook 5 is least priority, so it could in principle be skipped.

**Comment by msyriac** [comment]
No other comments, looks good, thanks!

**Comment by zonca** [comment]
ok, thank you, I'll go ahead with the kernel, then retest all the notebooks and make these fixes

**Comment by zonca** [comment]
@msyriac updated the kernel and tested all notebooks,

also I suggest to use the "Table of contents" plugin which is already installed at NERSC,
it also supports auto-numbering the sections, I think it helps a lot for longer notebooks:

![image](https://user-images.githubusercontent.com/383090/85478925-000d6b00-b572-11ea-9422-e3b2bc296d68.png)
